export const GET_CATEGORIES_ATTEMP = 'GET_CATEGORIES_ATTEMP';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_CATEGORIES_DESCRIPTION_ATTEMP =
  'GET_CATEGORIES_DESCRIPTION_ATTEMP';
export const GET_CATEGORIES_DESCRIPTION_SUCCESS =
  'GET_CATEGORIES_DESCRIPTION_SUCCESS';
export const GET_CATEGORIES_DESCRIPTION_FAILURE =
  'GET_CATEGORIES_DESCRIPTION_FAILURE';

export const ADD_TO_CART_ATTEMPT = 'ADD_TO_CART_ATTEMPT';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';


export const REMOVE_TO_CART_SUCCESS = 'REMOVE_TO_CART_SUCCESS';

export const UPDATE_CATEGORIES_SUCCESS = 'UPDATE_CATEGORIES_SUCCESS';
